config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
   }
  get 'teams/top'
  get 'teams/index'
  get 'teams/search'
  get 'users/search'
  root to: 'teams#top'
  resources :users do
    resources :teams
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  has_one_attached :avatar

  belongs_to :prefecture
  belongs_to :term
  belongs_to :level
  belongs_to :frequency
  belongs_to :registration

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/, message: '全角文字を使用してください' } do
    validates :name
  end
  with_options presence: true, format: { with: /\A[ァ-ヶ]+\z/, message: '全角カナ文字を使用してください' } do
    validates :name_kana
  end
  validates :avatar, presence: true
  validates :birthday, presence: true
  validates :prefecture_id, presence: true
  validates :term_id, presence: true
  validates :level_id, presence: true
  validates :frequency_id, presence: true
  validates :registration_id, presence: true
  
  validates :prefecture_id, :term_id, :level_id, :frequency_id, :registration_id, numericality: { other_than: 1 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    super
    resource.avatar.attach(account_update_params[:avatar]) if account_update_params[:avatar].present?
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :name, :name_kana, :birthday, :term_id, :level_id, :frequency_id, :registration_id, :prefecture_id,
                                 :city, :achievement)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :search_user, only: [:index, :search]

  def index
    @users = User.all
    @user = User.where(category_id: params[:id]).order('created_at DESC')
  end

  def new
   @user = User.new
  end

  def search
    @results = @p.result
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def search_user
    @p = User.ransack(params[:q])
  end

  def set_user_column
    @user_term_id = User.select('term_id').distinct  # 重複なくnameカラムのデータを取り出す
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :name, :name_kana, :birthday, :term_id, :level_id, :frequency_id, :registration_id, :prefecture_id,
                                 :city, :achievement)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>
<%= form_with model: @user, url: user_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>
  <% if @user.errors.any? %>
  <%= render 'shared/error_messages', model: f.object %>    
  <% end %>
  <div class="img-upload">
    <div class="weight-bold-text">
      登録画像
      <span class="indispensable">必須</span>
    </div>
    <div class="click-upload">
     <p>
       クリックしてファイルをアップロード
      </p>
     <%= f.file_field :avatar, id:"item-image" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :name, class:"input-name", id:"last-name", placeholder:"例) 山田太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>

  <div class="items-detail">
      <div class="form">
      <%= form_with(model: @user, url:new_user_registration_path, local: true) do |f| %>
        <div class="weight-bold-text">
          野球歴
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:term_id, Term.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        <div class="weight-bold-text">
          希望する野球レベル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:level_id, Level.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          希望活動頻度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:frequency_id, Frequency.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          選手登録希望
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:registration_id, Registration.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          お住まいの都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
      </div>
    </div>
    <% end %>

  <div class="form-group">
    <div class='form-text-wrap'>
        <label class="form-text">市区町村</label>
        <span class="indispensable">必須</span>
      </div>
    <div class='input-name-wrap'>
      <%= f.text_area :city, class:"input-name", id:"last-name", placeholder:"例) 新宿区" %>
    </div>
      <div class='form-text-wrap'>
        <label class="form-text">野球実績</label>
      </div>
    <div class='input-name-wrap'>
      <%= f.text_area :achievement, class:"input-name", id:"last-name", placeholder:"例) 全国大会出場経験あり" %>
    </div>
  </div>

  <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "会員登録" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/index.html.erb
<h1>
  メンバー・助っ人検索
</h1>
<%= search_form_for @p, url: users_search_path do |f| %>
<div class="search-form">
  <div class="search-group">
   <div class="search-block">
    <div class="search-content">
      <%= f.label :term_id_eq, '野球歴' %>
      <%= f.collection_select :term_id_eq, Term.all, :id, :name,  include_blank: '指定なし' %>
    </div>
    <div class="search-content">
      <%= f.label :level_id_eq, '希望する野球レベル'%>
      <%= f.collection_select :level_id_eq, Level.all, :id, :name,  include_blank: '指定なし' %>
    </div>
   </div>
   <div class="search-block">
    <div class="search-content">
      <%= f.label :frequency_id_eq, '希望活動頻度' %>
      <%= f.collection_select :frequency_id_eq, Frequency.all, :id, :name,  include_blank: '指定なし' %>
    </div>
    <div class="search-content">
      <%= f.label :prefecture_id_eq, '都道府県' %>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name,  include_blank: '指定なし' %>
    </div>
    </div>
  </div>
  <div class="search-button">
      <%= f.submit '検索' %>
  </div>
</div>

  <div class="sub-title">検索一覧</div>
  <div class="list-index">
  <% @users.each do |user| %>
  <div class='list'>
  <%= link_to user_path(user.id) , method: :get do %>

  <div class="member-index">
    <%= image_tag user.avatar, class: "item-img" %>
    <div class="member-group">
      <div class="member-detail">
      <%= user.name %>
      </div>
      <div class="member-detail">
      <%= user.term.name %>
      </div>
      <div class="member-detail">
      <%= user.level.name %>
      </div>
      <div class="member-detail">
      <%= user.frequency.name %>
      </div>
      <div class="member-detail">
      <%= user.prefecture.name %>
      </div>
    </div>
  </div>
  <% end %>
  </div>
  <% end %>
  </div>
<% end %>

app/views/users/search.html.erb
<h1 class="title">
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<div class="result">
<% if @results.length !=0 %>
  <% @results.each do |result| %>
  <div class='list'>
  <%= image_tag result.avatar, class: "item-img" %>
    <td>
    <br>
    <li class="member-index">
      <div class="menmber-detail">
      <%= result.name %>
      </div>
      <div class="menmber-detail">
      <%= result.term.name %>
      </div>
      <div class="menmber-detail">
      <%= result.level.name %>
      </div>
      <div class="menmber-detail">
      <%= result.frequency.name %>
      </div>
      <div class="menmber-detail">
      <%= result.prefecture.name %>
      </div>
    </li>
  </div>
  <% end %>
<% else %>
  該当する商品はありません
<% end %>
</div>

<div class="top-back">
<%= link_to 'トップページへ戻る', root_path%>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @user.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @user.avatar, class:"item-box-img" %>
    </div>
    <div class="item-price-box">
    </div>

    <div class="item-explain-box">
      <span><%= "メンバー詳細" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">氏名</th>
          <td class="detail-value"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">野球経歴</th>
          <td class="detail-value"><%= @user.term.name %></td>
        </tr>
        <tr>
          <th class="detail-item">希望する野球レベル</th>
          <td class="detail-value"><%= @user.level.name %></td>
        </tr>
        <tr>
          <th class="detail-item">希望活動頻度</th>
          <td class="detail-value"><%= @user.frequency.name %></td>
        </tr>
        <tr>
          <th class="detail-item">在住している都道府県</th>
          <td class="detail-value"><%= @user.prefecture.name %></td>
        <tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
</div>

<%= render "shared/footer" %>